[workspace]
members = [
    "src/led-roulette",
    "src/hello-world",
    "src/registers",
    "src/registers-unsafe-read",
    "src/registers-read",
    "src/registers-safe-manip",
    "src/registers-hal",
    "src/clocks-timers",
]
[profile.release]
codegen-units = 1
debug = true
lto = true
