[workspace]
members = [
    "src/led-roulette",
    "src/hello-world",
    "src/registers",
    "src/registers-unsafe-read",
    "src/registers-read",
]
[profile.release]
codegen-units = 1
debug = true
lto = true
